name: Build HeavyAI JDBC

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build JAR
      run: mvn clean package
      
    - name: Build Fat JAR
      run: mvn clean package -P fatjar
      
    - name: Upload JAR artifacts
      uses: actions/upload-artifact@v4
      with:
        name: heavyai-jdbc-jars
        path: target/*.jar
        retention-days: 30