name: Test HeavyAI JDBC

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      heavydb:
        image: heavyai/core-os-cpu
        ports:
          - 6274:6274
          - 6278:6278
        options: >-
          --health-cmd "nc -z localhost 6274 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
          --health-start-period 60s
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Wait for HeavyDB to be ready
      run: |
        echo "Waiting for HeavyDB JDBC port to be ready..."
        for i in {1..30}; do
          if nc -z localhost 6274; then
            echo "HeavyDB JDBC port 6274 is ready!"
            sleep 5  # Give it a few more seconds to fully initialize
            break
          fi
          echo "Waiting for port 6274... ($i/30)"
          sleep 10
        done
        
    - name: Run tests
      run: mvn test -DskipTests=false
      
    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests
        path: target/surefire-reports/*.xml
        reporter: java-junit